# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.model2a45b6d9d77224d9a1e13d0b698f6c4b200_response import Model2a45b6d9d77224d9a1e13d0b698f6c4b200Response

class TestModel2a45b6d9d77224d9a1e13d0b698f6c4b200Response(unittest.TestCase):
    """Model2a45b6d9d77224d9a1e13d0b698f6c4b200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model2a45b6d9d77224d9a1e13d0b698f6c4b200Response:
        """Test Model2a45b6d9d77224d9a1e13d0b698f6c4b200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model2a45b6d9d77224d9a1e13d0b698f6c4b200Response`
        """
        model = Model2a45b6d9d77224d9a1e13d0b698f6c4b200Response()
        if include_optional:
            return Model2a45b6d9d77224d9a1e13d0b698f6c4b200Response(
                var_property = None,
                selections = [
                    null
                    ],
                timestamp = 56
            )
        else:
            return Model2a45b6d9d77224d9a1e13d0b698f6c4b200Response(
                var_property = None,
                selections = [
                    null
                    ],
                timestamp = 56,
        )
        """

    def testModel2a45b6d9d77224d9a1e13d0b698f6c4b200Response(self):
        """Test Model2a45b6d9d77224d9a1e13d0b698f6c4b200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
