# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.key_api import KeyApi


class TestKeyApi(unittest.TestCase):
    """KeyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KeyApi()

    def tearDown(self) -> None:
        pass

    def test_c6ccbb0a05ebf3b307c82a4c89275e52(self) -> None:
        """Test case for c6ccbb0a05ebf3b307c82a4c89275e52

        Get any Key selection
        """
        pass

    def test_call_0d6dae59c9b3419c18d2a4ca0da757e6(self) -> None:
        """Test case for call_0d6dae59c9b3419c18d2a4ca0da757e6

        Get current key log history
        """
        pass

    def test_e6d387f16971004628eeca2d6473f825(self) -> None:
        """Test case for e6d387f16971004628eeca2d6473f825

        Get current key info
        """
        pass


if __name__ == '__main__':
    unittest.main()
