# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.market_rental_details import MarketRentalDetails

class TestMarketRentalDetails(unittest.TestCase):
    """MarketRentalDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketRentalDetails:
        """Test MarketRentalDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketRentalDetails`
        """
        model = MarketRentalDetails()
        if include_optional:
            return MarketRentalDetails(
                listings = [
                    openapi_client.models.market_rental_details_listings_inner.MarketRentalDetails_listings_inner(
                        happy = 56, 
                        cost = 56, 
                        cost_per_day = 56, 
                        rental_period = 56, 
                        market_price = 56, 
                        upkeep = 56, 
                        modifications = [
                            'Hot Tub'
                            ], )
                    ],
                var_property = openapi_client.models.basic_property.BasicProperty(
                    id = 56, 
                    name = '', )
            )
        else:
            return MarketRentalDetails(
                listings = [
                    openapi_client.models.market_rental_details_listings_inner.MarketRentalDetails_listings_inner(
                        happy = 56, 
                        cost = 56, 
                        cost_per_day = 56, 
                        rental_period = 56, 
                        market_price = 56, 
                        upkeep = 56, 
                        modifications = [
                            'Hot Tub'
                            ], )
                    ],
                var_property = openapi_client.models.basic_property.BasicProperty(
                    id = 56, 
                    name = '', ),
        )
        """

    def testMarketRentalDetails(self):
        """Test MarketRentalDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
