# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.report_report_report import ReportReportReport

class TestReportReportReport(unittest.TestCase):
    """ReportReportReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportReportReport:
        """Test ReportReportReport
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportReportReport`
        """
        model = ReportReportReport()
        if include_optional:
            return ReportReportReport(
                money = 56,
                strength = 56,
                speed = 56,
                dexterity = 56,
                defense = 56,
                total = 56,
                top = [
                    openapi_client.models.report_warrant_details.ReportWarrantDetails(
                        id = 56, 
                        name = '', 
                        warrant = 56, )
                    ],
                notable = [
                    openapi_client.models.report_warrant_details.ReportWarrantDetails(
                        id = 56, 
                        name = '', 
                        warrant = 56, )
                    ],
                factions = [
                    openapi_client.models.report_history_faction.ReportHistoryFaction(
                        id = 56, 
                        name = '', 
                        joined = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        left = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                companies = [
                    openapi_client.models.report_history_company.ReportHistoryCompany(
                        id = 56, 
                        name = '', 
                        joined = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        left = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                friends = [
                    openapi_client.models.report_friend_or_foe_user.ReportFriendOrFoeUser(
                        id = 56, 
                        name = '', )
                    ],
                enemies = [
                    openapi_client.models.report_friend_or_foe_user.ReportFriendOrFoeUser(
                        id = 56, 
                        name = '', )
                    ],
                balance = 56,
                employees = 56,
                wages = openapi_client.models.report_company_financials_wages.ReportCompanyFinancials_wages(
                    highest = 56, 
                    lowest = 56, 
                    average = 56, ),
                level = 56,
                items = [
                    openapi_client.models.report_stock_analysis_items_inner.ReportStockAnalysis_items_inner(
                        country = 'Mexico', 
                        item = openapi_client.models.report_stock_analysis_items_inner_item.ReportStockAnalysis_items_inner_item(
                            id = 56, 
                            name = '', 
                            price = 56, 
                            value = 56, 
                            due = 56, ), 
                        trip_duration = 56, 
                        hourly_profit = 56, )
                    ],
                bounties = [
                    openapi_client.models.report_anonymous_bounties_bounties_inner.ReportAnonymousBounties_bounties_inner(
                        text = '', 
                        bounty = 56, 
                        user = openapi_client.models.report_anonymous_bounties_bounties_inner_user.ReportAnonymousBounties_bounties_inner_user(
                            id = 56, 
                            name = '', ), )
                    ],
                amount = 56,
                until = 56
            )
        else:
            return ReportReportReport(
                money = 56,
                strength = 56,
                speed = 56,
                dexterity = 56,
                defense = 56,
                total = 56,
                top = [
                    openapi_client.models.report_warrant_details.ReportWarrantDetails(
                        id = 56, 
                        name = '', 
                        warrant = 56, )
                    ],
                notable = [
                    openapi_client.models.report_warrant_details.ReportWarrantDetails(
                        id = 56, 
                        name = '', 
                        warrant = 56, )
                    ],
                factions = [
                    openapi_client.models.report_history_faction.ReportHistoryFaction(
                        id = 56, 
                        name = '', 
                        joined = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        left = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                companies = [
                    openapi_client.models.report_history_company.ReportHistoryCompany(
                        id = 56, 
                        name = '', 
                        joined = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        left = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                friends = [
                    openapi_client.models.report_friend_or_foe_user.ReportFriendOrFoeUser(
                        id = 56, 
                        name = '', )
                    ],
                enemies = [
                    openapi_client.models.report_friend_or_foe_user.ReportFriendOrFoeUser(
                        id = 56, 
                        name = '', )
                    ],
                balance = 56,
                employees = 56,
                wages = openapi_client.models.report_company_financials_wages.ReportCompanyFinancials_wages(
                    highest = 56, 
                    lowest = 56, 
                    average = 56, ),
                level = 56,
                items = [
                    openapi_client.models.report_stock_analysis_items_inner.ReportStockAnalysis_items_inner(
                        country = 'Mexico', 
                        item = openapi_client.models.report_stock_analysis_items_inner_item.ReportStockAnalysis_items_inner_item(
                            id = 56, 
                            name = '', 
                            price = 56, 
                            value = 56, 
                            due = 56, ), 
                        trip_duration = 56, 
                        hourly_profit = 56, )
                    ],
                bounties = [
                    openapi_client.models.report_anonymous_bounties_bounties_inner.ReportAnonymousBounties_bounties_inner(
                        text = '', 
                        bounty = 56, 
                        user = openapi_client.models.report_anonymous_bounties_bounties_inner_user.ReportAnonymousBounties_bounties_inner_user(
                            id = 56, 
                            name = '', ), )
                    ],
                amount = 56,
                until = 56,
        )
        """

    def testReportReportReport(self):
        """Test ReportReportReport"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
