# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.faction_api import FactionApi


class TestFactionApi(unittest.TestCase):
    """FactionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FactionApi()

    def tearDown(self) -> None:
        pass

    def test_a09da2d5f951a49d974dbec3149b3a24(self) -> None:
        """Test case for a09da2d5f951a49d974dbec3149b3a24

        Get a faction's basic details
        """
        pass

    def test_a775ca7831f4cad88c308be28f50e597(self) -> None:
        """Test case for a775ca7831f4cad88c308be28f50e597

        Get a faction's hall of fame rankings.
        """
        pass

    def test_ae7f06db4618d3e7927fd700cfa58f16(self) -> None:
        """Test case for ae7f06db4618d3e7927fd700cfa58f16

        Get faction warfare
        """
        pass

    def test_aee5679a81c6a7bcd3862c0aafd6b558(self) -> None:
        """Test case for aee5679a81c6a7bcd3862c0aafd6b558

        Get your faction's current chain
        """
        pass

    def test_b31cce9916e77431c08822844a0dbf2b(self) -> None:
        """Test case for b31cce9916e77431c08822844a0dbf2b

        Get your faction's wars & pacts details
        """
        pass

    def test_b4867db9b02fa7dcd31b2073f2a936ce(self) -> None:
        """Test case for b4867db9b02fa7dcd31b2073f2a936ce

        Get a specific organized crime
        """
        pass

    def test_bf56fb8aba4d6810e9b96402e25b931d(self) -> None:
        """Test case for bf56fb8aba4d6810e9b96402e25b931d

        Get a list of your faction's territories
        """
        pass

    def test_c370823454d5ea28fc0df9a5b6a24c54(self) -> None:
        """Test case for c370823454d5ea28fc0df9a5b6a24c54

        Get a faction's wars & pacts details
        """
        pass

    def test_call_01c192f9b41ce29372df54667bea2b43(self) -> None:
        """Test case for call_01c192f9b41ce29372df54667bea2b43

        Search factions by name or other criteria
        """
        pass

    def test_call_0258963246159d1e3e54547c32aac7c8(self) -> None:
        """Test case for call_0258963246159d1e3e54547c32aac7c8

        Get territory wars history for your faction
        """
        pass

    def test_call_03d304564e4f84e3f258e5b8059bcc22(self) -> None:
        """Test case for call_03d304564e4f84e3f258e5b8059bcc22

        Get a list of your faction's members
        """
        pass

    def test_call_065bcbaa654fc44ce7b8ea574b84f7b9(self) -> None:
        """Test case for call_065bcbaa654fc44ce7b8ea574b84f7b9

        """
        pass

    def test_call_1da64889366de71140f2c15ad14b67b1(self) -> None:
        """Test case for call_1da64889366de71140f2c15ad14b67b1

        Get your faction's news details
        """
        pass

    def test_call_21a251c2ec9f6c93b89fb715196bb8be(self) -> None:
        """Test case for call_21a251c2ec9f6c93b89fb715196bb8be

        Get a chain report
        """
        pass

    def test_call_3ca2c0319f960b728ffece8e322cf40f(self) -> None:
        """Test case for call_3ca2c0319f960b728ffece8e322cf40f

        Get your faction's & member's balance details
        """
        pass

    def test_call_40eb7627818eb777fdc713ed78209c6b(self) -> None:
        """Test case for call_40eb7627818eb777fdc713ed78209c6b

        Get your faction's challenge contributors
        """
        pass

    def test_call_486fcda26ed1aa6aba8ec7091080723b(self) -> None:
        """Test case for call_486fcda26ed1aa6aba8ec7091080723b

        Get your faction's detailed revives
        """
        pass

    def test_call_4dce518364dad91fb3503e0382adfadf(self) -> None:
        """Test case for call_4dce518364dad91fb3503e0382adfadf

        Get a list of a faction's territories
        """
        pass

    def test_call_4e8aeafde7b5fc9918d166cda150fa91(self) -> None:
        """Test case for call_4e8aeafde7b5fc9918d166cda150fa91

        Get territory war details
        """
        pass

    def test_call_4f5d624a86e2d389a7a738b6b3ce8c9e(self) -> None:
        """Test case for call_4f5d624a86e2d389a7a738b6b3ce8c9e

        Get ranked wars history for your faction
        """
        pass

    def test_call_5b6646714e5ae1cc397bdec877f55691(self) -> None:
        """Test case for call_5b6646714e5ae1cc397bdec877f55691

        Get a faction's ranked wars history
        """
        pass

    def test_call_614a2f2bdd7fb6df778b7657c75d1113(self) -> None:
        """Test case for call_614a2f2bdd7fb6df778b7657c75d1113

        Get your faction's latest chain report
        """
        pass

    def test_call_627df4d7d8b91c62dacb66ff373aab5c(self) -> None:
        """Test case for call_627df4d7d8b91c62dacb66ff373aab5c

        Get current server time
        """
        pass

    def test_call_67622543dbbc4857f1ea575be5af7fcd(self) -> None:
        """Test case for call_67622543dbbc4857f1ea575be5af7fcd

        Get a faction's raids history
        """
        pass

    def test_call_6a2b0604d0ebe31933f93facfa69f171(self) -> None:
        """Test case for call_6a2b0604d0ebe31933f93facfa69f171

        Get raids history for your faction
        """
        pass

    def test_call_72e5db8a773908fedff4bb002f3f4406(self) -> None:
        """Test case for call_72e5db8a773908fedff4bb002f3f4406

        Get your faction's organized crimes
        """
        pass

    def test_call_76ce672d50a66fc0a832f9088e5436af(self) -> None:
        """Test case for call_76ce672d50a66fc0a832f9088e5436af

        Get a faction's territory wars history
        """
        pass

    def test_call_77dae3b930e2e2f9f7608567db0b94f4(self) -> None:
        """Test case for call_77dae3b930e2e2f9f7608567db0b94f4

        Get your faction's positions details
        """
        pass

    def test_call_806d9dc7e5fcf9e1ee9c3cdf7f035392(self) -> None:
        """Test case for call_806d9dc7e5fcf9e1ee9c3cdf7f035392

        Get your faction's challenges stats
        """
        pass

    def test_call_8551280aaaf9819aa94be5c469a523de(self) -> None:
        """Test case for call_8551280aaaf9819aa94be5c469a523de

        Get your faction's simplified attacks
        """
        pass

    def test_call_959f415abf48cb753414cec179b1b039(self) -> None:
        """Test case for call_959f415abf48cb753414cec179b1b039

        Get your faction's upgrades
        """
        pass

    def test_call_99a899c0094645475fd6254b423fea43(self) -> None:
        """Test case for call_99a899c0094645475fd6254b423fea43

        Get a list of a faction's members
        """
        pass

    def test_call_9a48477c16e86235efce00a11d56510f(self) -> None:
        """Test case for call_9a48477c16e86235efce00a11d56510f

        Get raid war details
        """
        pass

    def test_call_9f7dccb023d81a8da7f5f6a359658a64(self) -> None:
        """Test case for call_9f7dccb023d81a8da7f5f6a359658a64

        Get your faction's applications
        """
        pass

    def test_cb5b38ba64c389e706526df8bc8af9b6(self) -> None:
        """Test case for cb5b38ba64c389e706526df8bc8af9b6

        Get your faction's detailed attacks
        """
        pass

    def test_db49842d88e193777dc695e54769113e(self) -> None:
        """Test case for db49842d88e193777dc695e54769113e

        Get ranked war details
        """
        pass

    def test_dd88ca1ffafed80457916da5298a3422(self) -> None:
        """Test case for dd88ca1ffafed80457916da5298a3422

        Get a list of a faction's completed chains
        """
        pass

    def test_dd89e28b1f1ed88853b09ecc982e4e66(self) -> None:
        """Test case for dd89e28b1f1ed88853b09ecc982e4e66

        Get any Faction selection
        """
        pass

    def test_dfc0adb55af4aeeeebc2d82309c71eea(self) -> None:
        """Test case for dfc0adb55af4aeeeebc2d82309c71eea

        Get a list of your faction's completed chains
        """
        pass

    def test_e104b0b606664d06d9638111702301f3(self) -> None:
        """Test case for e104b0b606664d06d9638111702301f3

        Get your faction's hall of fame rankings.
        """
        pass

    def test_e8bd37f10cc5e0e8d6694bb306f3a1e4(self) -> None:
        """Test case for e8bd37f10cc5e0e8d6694bb306f3a1e4

        Get faction reports
        """
        pass

    def test_ec8f82e15a321adbb20e615024d9dff6(self) -> None:
        """Test case for ec8f82e15a321adbb20e615024d9dff6

        Get a faction's current chain
        """
        pass

    def test_f17a4064779e8de5200238816c233c02(self) -> None:
        """Test case for f17a4064779e8de5200238816c233c02

        Get your faction's simplified revives
        """
        pass

    def test_f750d219e54329ae300c4db384dd5dcd(self) -> None:
        """Test case for f750d219e54329ae300c4db384dd5dcd

        Get a list of current rackets
        """
        pass

    def test_fa6b3fbb14e5f3a71279b058bd751754(self) -> None:
        """Test case for fa6b3fbb14e5f3a71279b058bd751754

        Get a list of your faction's territories
        """
        pass

    def test_fb363bf0e1d54296bd4d5dd554ad9825(self) -> None:
        """Test case for fb363bf0e1d54296bd4d5dd554ad9825

        Get your faction's basic details
        """
        pass


if __name__ == '__main__':
    unittest.main()
