# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.property_api import PropertyApi


class TestPropertyApi(unittest.TestCase):
    """PropertyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PropertyApi()

    def tearDown(self) -> None:
        pass

    def test_call_2a45b6d9d77224d9a1e13d0b698f6c4b(self) -> None:
        """Test case for call_2a45b6d9d77224d9a1e13d0b698f6c4b

        Get any property selection
        """
        pass

    def test_call_423c130a5cdf6bc801c42537c07fddec(self) -> None:
        """Test case for call_423c130a5cdf6bc801c42537c07fddec

        Get current server time
        """
        pass

    def test_call_87bd73ddaf3749bce7cbf5aa28e921e2(self) -> None:
        """Test case for call_87bd73ddaf3749bce7cbf5aa28e921e2

        Get a specific property
        """
        pass

    def test_call_87fe6e3a7ec186e108922fed781c8d6d(self) -> None:
        """Test case for call_87fe6e3a7ec186e108922fed781c8d6d

        Get all available property selections
        """
        pass


if __name__ == '__main__':
    unittest.main()
