# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.forum_api import ForumApi


class TestForumApi(unittest.TestCase):
    """ForumApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ForumApi()

    def tearDown(self) -> None:
        pass

    def test_a4618a3901c01413c14b75e984495a9b(self) -> None:
        """Test case for a4618a3901c01413c14b75e984495a9b

        Get specific thread details
        """
        pass

    def test_call_21915cf0228ce3677261cdce27fb39e2(self) -> None:
        """Test case for call_21915cf0228ce3677261cdce27fb39e2

        Get any Forum selection
        """
        pass

    def test_call_715cb3a4df0a9bf8094a53dc3259b633(self) -> None:
        """Test case for call_715cb3a4df0a9bf8094a53dc3259b633

        Get threads for specific public forum category or categories
        """
        pass

    def test_call_79b21191b87da275f3b87a7a1a233d04(self) -> None:
        """Test case for call_79b21191b87da275f3b87a7a1a233d04

        Get publicly available forum categories
        """
        pass

    def test_call_9c5eeb1aebb102b7c62fab11974c359a(self) -> None:
        """Test case for call_9c5eeb1aebb102b7c62fab11974c359a

        Get specific forum thread posts
        """
        pass

    def test_d2d64a69cedfdce19a50eff117e2c166(self) -> None:
        """Test case for d2d64a69cedfdce19a50eff117e2c166

        Get threads across all forum categories
        """
        pass

    def test_ec72c2a8cd96c88e4d228221bf6bf42f(self) -> None:
        """Test case for ec72c2a8cd96c88e4d228221bf6bf42f

        Get current server time
        """
        pass

    def test_f0805d0b7ad26c62ddd2fa8d0d332ba4(self) -> None:
        """Test case for f0805d0b7ad26c62ddd2fa8d0d332ba4

        Get all available forum selections
        """
        pass


if __name__ == '__main__':
    unittest.main()
