# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.faction_raids_response import FactionRaidsResponse

class TestFactionRaidsResponse(unittest.TestCase):
    """FactionRaidsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FactionRaidsResponse:
        """Test FactionRaidsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FactionRaidsResponse`
        """
        model = FactionRaidsResponse()
        if include_optional:
            return FactionRaidsResponse(
                raids = [
                    openapi_client.models.faction_raid_warfare.FactionRaidWarfare(
                        id = 56, 
                        start = 56, 
                        end = 56, 
                        aggressor = openapi_client.models.faction_raid_warfare_faction.FactionRaidWarfareFaction(
                            id = 56, 
                            name = '', 
                            score = 1.337, 
                            chain = 56, ), 
                        defender = openapi_client.models.faction_raid_warfare_faction.FactionRaidWarfareFaction(
                            id = 56, 
                            name = '', 
                            score = 1.337, 
                            chain = 56, ), )
                    ],
                metadata = openapi_client.models.request_metadata_with_links.RequestMetadataWithLinks(
                    links = openapi_client.models.request_links.RequestLinks(
                        next = '', 
                        prev = '', ), )
            )
        else:
            return FactionRaidsResponse(
                raids = [
                    openapi_client.models.faction_raid_warfare.FactionRaidWarfare(
                        id = 56, 
                        start = 56, 
                        end = 56, 
                        aggressor = openapi_client.models.faction_raid_warfare_faction.FactionRaidWarfareFaction(
                            id = 56, 
                            name = '', 
                            score = 1.337, 
                            chain = 56, ), 
                        defender = openapi_client.models.faction_raid_warfare_faction.FactionRaidWarfareFaction(
                            id = 56, 
                            name = '', 
                            score = 1.337, 
                            chain = 56, ), )
                    ],
                metadata = openapi_client.models.request_metadata_with_links.RequestMetadataWithLinks(
                    links = openapi_client.models.request_links.RequestLinks(
                        next = '', 
                        prev = '', ), ),
        )
        """

    def testFactionRaidsResponse(self):
        """Test FactionRaidsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
