# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.racing_api import RacingApi


class TestRacingApi(unittest.TestCase):
    """RacingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RacingApi()

    def tearDown(self) -> None:
        pass

    def test_ab5b44b00bf70d7a8587a3c2c9deeb17(self) -> None:
        """Test case for ab5b44b00bf70d7a8587a3c2c9deeb17

        Get cars and their racing stats
        """
        pass

    def test_c9e76cf48aa3c4bac4c8b33f1c0c9a17(self) -> None:
        """Test case for c9e76cf48aa3c4bac4c8b33f1c0c9a17

        Get all possible car upgrades
        """
        pass

    def test_call_39b8ce36e3fffc9e2aa1d0aed9ebccda(self) -> None:
        """Test case for call_39b8ce36e3fffc9e2aa1d0aed9ebccda

        Get any Racing selection
        """
        pass

    def test_call_4be921a67d32b5e82c68835ef56175d0(self) -> None:
        """Test case for call_4be921a67d32b5e82c68835ef56175d0

        Get races
        """
        pass

    def test_call_5fbc62db3b9380b155d7e33100620da7(self) -> None:
        """Test case for call_5fbc62db3b9380b155d7e33100620da7

        Get track records
        """
        pass

    def test_call_6e4507cc442d6f099d0170b78a35bf8d(self) -> None:
        """Test case for call_6e4507cc442d6f099d0170b78a35bf8d

        Get race tracks and descriptions
        """
        pass

    def test_call_76925256951bb63fd28534c8c479b27b(self) -> None:
        """Test case for call_76925256951bb63fd28534c8c479b27b

        Get specific race details
        """
        pass

    def test_call_8bd16be9aa517fedf717c9a79ff47e2c(self) -> None:
        """Test case for call_8bd16be9aa517fedf717c9a79ff47e2c

        Get all available racing selections
        """
        pass

    def test_eb1ae216aa2949a8db0702df474d174c(self) -> None:
        """Test case for eb1ae216aa2949a8db0702df474d174c

        Get current server time
        """
        pass


if __name__ == '__main__':
    unittest.main()
