# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.key_info_response import KeyInfoResponse

class TestKeyInfoResponse(unittest.TestCase):
    """KeyInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KeyInfoResponse:
        """Test KeyInfoResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KeyInfoResponse`
        """
        model = KeyInfoResponse()
        if include_optional:
            return KeyInfoResponse(
                info = openapi_client.models.key_info_response_info.KeyInfoResponse_info(
                    selections = openapi_client.models.key_info_response_info_selections.KeyInfoResponse_info_selections(
                        company = [
                            ''
                            ], 
                        faction = [
                            null
                            ], 
                        market = [
                            null
                            ], 
                        property = [
                            ''
                            ], 
                        torn = [
                            null
                            ], 
                        user = [
                            null
                            ], 
                        racing = [
                            null
                            ], 
                        forum = [
                            null
                            ], 
                        key = [
                            null
                            ], ), 
                    user = openapi_client.models.key_info_response_info_user.KeyInfoResponse_info_user(
                        faction_id = 56, 
                        company_id = 56, 
                        id = 56, ), 
                    access = openapi_client.models.key_info_response_info_access.KeyInfoResponse_info_access(
                        level = 56, 
                        type = 'Custom', 
                        faction = True, 
                        company = True, ), )
            )
        else:
            return KeyInfoResponse(
                info = openapi_client.models.key_info_response_info.KeyInfoResponse_info(
                    selections = openapi_client.models.key_info_response_info_selections.KeyInfoResponse_info_selections(
                        company = [
                            ''
                            ], 
                        faction = [
                            null
                            ], 
                        market = [
                            null
                            ], 
                        property = [
                            ''
                            ], 
                        torn = [
                            null
                            ], 
                        user = [
                            null
                            ], 
                        racing = [
                            null
                            ], 
                        forum = [
                            null
                            ], 
                        key = [
                            null
                            ], ), 
                    user = openapi_client.models.key_info_response_info_user.KeyInfoResponse_info_user(
                        faction_id = 56, 
                        company_id = 56, 
                        id = 56, ), 
                    access = openapi_client.models.key_info_response_info_access.KeyInfoResponse_info_access(
                        level = 56, 
                        type = 'Custom', 
                        faction = True, 
                        company = True, ), ),
        )
        """

    def testKeyInfoResponse(self):
        """Test KeyInfoResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
