# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dd89e28b1f1ed88853b09ecc982e4e66200_response import Dd89e28b1f1ed88853b09ecc982e4e66200Response

class TestDd89e28b1f1ed88853b09ecc982e4e66200Response(unittest.TestCase):
    """Dd89e28b1f1ed88853b09ecc982e4e66200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dd89e28b1f1ed88853b09ecc982e4e66200Response:
        """Test Dd89e28b1f1ed88853b09ecc982e4e66200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dd89e28b1f1ed88853b09ecc982e4e66200Response`
        """
        model = Dd89e28b1f1ed88853b09ecc982e4e66200Response()
        if include_optional:
            return Dd89e28b1f1ed88853b09ecc982e4e66200Response(
                hof = openapi_client.models.faction_hof_stats.FactionHofStats(
                    rank = openapi_client.models.hof_value_string.HofValueString(
                        value = '', 
                        rank = 56, ), 
                    respect = openapi_client.models.hof_value.HofValue(
                        value = 56, 
                        rank = 56, ), 
                    chain = openapi_client.models.hof_value.HofValue(
                        value = 56, 
                        rank = 56, ), ),
                members = [
                    openapi_client.models.faction_member.FactionMember(
                        id = 56, 
                        name = '', 
                        position = '', 
                        level = 56, 
                        days_in_faction = 56, 
                        is_revivable = True, 
                        is_on_wall = True, 
                        is_in_oc = True, 
                        has_early_discharge = True, 
                        last_action = openapi_client.models.user_last_action.UserLastAction(
                            status = '', 
                            timestamp = 56, 
                            relative = '', ), 
                        status = openapi_client.models.user_status.UserStatus(
                            description = '', 
                            details = '', 
                            state = '', 
                            until = 56, ), 
                        revive_setting = 'Everyone', )
                    ],
                basic = openapi_client.models.faction_basic.FactionBasic(
                    id = 56, 
                    name = '', 
                    tag = '', 
                    tag_image = '', 
                    leader_id = 56, 
                    co_leader_id = 56, 
                    respect = 56, 
                    days_old = 56, 
                    capacity = 56, 
                    members = 56, 
                    is_enlisted = True, 
                    rank = openapi_client.models.faction_rank.FactionRank(
                        level = 56, 
                        name = '', 
                        division = 56, 
                        position = 56, 
                        wins = 56, ), 
                    best_chain = 56, ),
                pacts = [
                    openapi_client.models.faction_pact.FactionPact(
                        faction_id = 56, 
                        faction_name = '', 
                        until = '', )
                    ],
                wars = openapi_client.models.faction_wars.FactionWars(
                    ranked = openapi_client.models.faction_ranked_war.FactionRankedWar(
                        war_id = 56, 
                        start = 56, 
                        end = 56, 
                        target = 56, 
                        winner = 56, 
                        factions = [
                            openapi_client.models.faction_ranked_war_participant.FactionRankedWarParticipant(
                                id = 56, 
                                name = '', 
                                score = 56, 
                                chain = 56, )
                            ], ), 
                    raids = [
                        openapi_client.models.faction_raid_war.FactionRaidWar(
                            war_id = 56, 
                            start = 56, 
                            end = 56, 
                            factions = [
                                openapi_client.models.faction_raid_war_participant.FactionRaidWarParticipant(
                                    id = 56, 
                                    name = '', 
                                    score = 56, 
                                    chain = 56, 
                                    is_aggressor = True, )
                                ], )
                        ], 
                    territory = [
                        openapi_client.models.faction_territory_war.FactionTerritoryWar(
                            war_id = 56, 
                            territory = '', 
                            start = 56, 
                            end = 56, 
                            target = 56, 
                            winner = 56, 
                            factions = [
                                openapi_client.models.faction_territory_war_participant.FactionTerritoryWarParticipant(
                                    id = 56, 
                                    name = '', 
                                    score = 56, 
                                    chain = 56, 
                                    is_aggressor = True, 
                                    player_ids = [
                                        56
                                        ], )
                                ], )
                        ], ),
                news = [
                    openapi_client.models.faction_news.FactionNews(
                        id = '', 
                        text = '', 
                        timestamp = 56, )
                    ],
                metadata = openapi_client.models.request_metadata_with_links.RequestMetadataWithLinks(
                    links = openapi_client.models.request_links.RequestLinks(
                        next = '', 
                        prev = '', ), ),
                revives = [
                    openapi_client.models.revive_simplified.ReviveSimplified(
                        id = 56, 
                        reviver = openapi_client.models.revive_simplified_reviver.ReviveSimplified_reviver(
                            id = 56, 
                            faction_id = 56, ), 
                        target = openapi_client.models.revive_simplified_target.ReviveSimplified_target(
                            id = 56, 
                            faction_id = 56, 
                            hospital_reason = '', 
                            early_discharge = True, 
                            last_action = 56, 
                            online_status = '', ), 
                        success_chance = 1.337, 
                        result = '', 
                        timestamp = 56, )
                    ],
                territorywars = None,
                attacks = [
                    openapi_client.models.attack_simplified.AttackSimplified(
                        id = 56, 
                        code = '', 
                        started = 56, 
                        ended = 56, 
                        attacker = openapi_client.models.attack_player_simplified.AttackPlayerSimplified(
                            id = 56, 
                            faction_id = 56, ), 
                        defender = openapi_client.models.attack_player_simplified.AttackPlayerSimplified(
                            id = 56, 
                            faction_id = 56, ), 
                        result = 'None', 
                        respect_gain = 1.337, 
                        respect_loss = 1.337, )
                    ],
                balance = openapi_client.models.faction_balance.FactionBalance(
                    faction = openapi_client.models.faction_balance_faction.FactionBalance_faction(
                        money = 56, 
                        points = 56, 
                        scope = 56, ), 
                    members = [
                        openapi_client.models.faction_balance_members_inner.FactionBalance_members_inner(
                            id = 56, 
                            username = '', 
                            money = 56, 
                            points = 56, )
                        ], ),
                raidreport = [
                    openapi_client.models.faction_raid_report.FactionRaidReport(
                        id = 56, 
                        start = 56, 
                        end = 56, 
                        aggressor = openapi_client.models.faction_raid_report_faction.FactionRaidReportFaction(
                            id = 56, 
                            name = '', 
                            score = 1.337, 
                            attackers = [
                                openapi_client.models.faction_raid_report_attacker.FactionRaidReportAttacker(
                                    user = openapi_client.models.report_friend_or_foe_user.ReportFriendOrFoeUser(
                                        id = 56, 
                                        name = '', ), 
                                    attacks = 56, 
                                    damage = 1.337, )
                                ], 
                            non_attackers = [
                                openapi_client.models.report_friend_or_foe_user.ReportFriendOrFoeUser(
                                    id = 56, 
                                    name = '', )
                                ], ), 
                        defender = openapi_client.models.faction_raid_report_faction.FactionRaidReportFaction(
                            id = 56, 
                            name = '', 
                            score = 1.337, 
                            attackers = [
                                openapi_client.models.faction_raid_report_attacker.FactionRaidReportAttacker(
                                    user = , 
                                    attacks = 56, 
                                    damage = 1.337, )
                                ], 
                            non_attackers = [
                                
                                ], ), )
                    ],
                territory_ownership = [
                    openapi_client.models.faction_territory_ownership.FactionTerritoryOwnership(
                        id = '', 
                        owned_by = 56, 
                        acquired_at = 56, )
                    ],
                positions = [
                    openapi_client.models.faction_position.FactionPosition(
                        name = '', 
                        is_default = True, 
                        abilities = [
                            'Medical Item Usage'
                            ], )
                    ],
                applications = [
                    openapi_client.models.faction_application.FactionApplication(
                        id = 56, 
                        user = openapi_client.models.faction_application_user.FactionApplication_user(
                            id = 56, 
                            name = '', 
                            level = 56, 
                            stats = openapi_client.models.faction_application_user_stats.FactionApplication_user_stats(
                                strength = 56, 
                                speed = 56, 
                                dexterity = 56, 
                                defense = 56, ), ), 
                        message = '', 
                        valid_until = 56, 
                        status = 'accepted', )
                    ],
                chain = openapi_client.models.faction_ongoing_chain.FactionOngoingChain(
                    id = 56, 
                    current = 56, 
                    max = 56, 
                    timeout = 56, 
                    modifier = 1.337, 
                    cooldown = 56, 
                    start = 56, 
                    end = 56, ),
                chains = [
                    openapi_client.models.faction_chain.FactionChain(
                        id = 56, 
                        chain = 56, 
                        respect = 1.337, 
                        start = 56, 
                        end = 56, )
                    ],
                chainreport = openapi_client.models.faction_chain_report.FactionChainReport(
                    id = 56, 
                    faction_id = 56, 
                    start = 56, 
                    end = 56, 
                    details = openapi_client.models.faction_chain_report_details.FactionChainReportDetails(
                        chain = 56, 
                        respect = 1.337, 
                        members = 56, 
                        targets = 56, 
                        war = 56, 
                        best = 1.337, 
                        leave = 56, 
                        mug = 56, 
                        hospitalize = 56, 
                        assists = 56, 
                        retaliations = 56, 
                        overseas = 56, 
                        draws = 56, 
                        escapes = 56, 
                        losses = 56, ), 
                    bonuses = [
                        openapi_client.models.faction_chain_report_bonus.FactionChainReportBonus(
                            attacker_id = 56, 
                            defender_id = 56, 
                            chain = 56, 
                            respect = 56, )
                        ], 
                    attackers = [
                        openapi_client.models.faction_chain_report_attacker.FactionChainReportAttacker(
                            id = 56, 
                            respect = openapi_client.models.faction_chain_report_attacker_respect.FactionChainReportAttackerRespect(
                                total = 1.337, 
                                average = 1.337, 
                                best = 1.337, ), 
                            attacks = openapi_client.models.faction_chain_report_attacker_attacks.FactionChainReportAttackerAttacks(
                                total = 56, 
                                leave = 56, 
                                mug = 56, 
                                hospitalize = 56, 
                                assists = 56, 
                                retaliations = 56, 
                                overseas = 56, 
                                draws = 56, 
                                escapes = 56, 
                                losses = 56, 
                                war = 56, 
                                bonuses = 56, ), )
                        ], 
                    non_attackers = [
                        56
                        ], ),
                crimes = [
                    openapi_client.models.faction_crime.FactionCrime(
                        id = 56, 
                        previous_crime_id = 56, 
                        name = '', 
                        difficulty = 56, 
                        status = 'Recruiting', 
                        created_at = 56, 
                        planning_at = 56, 
                        ready_at = 56, 
                        expired_at = 56, 
                        executed_at = 56, 
                        slots = [
                            openapi_client.models.faction_crime_slot.FactionCrimeSlot(
                                position = '', 
                                position_id = 'P1', 
                                position_number = 56, 
                                item_requirement = openapi_client.models.faction_crime_slot_item_requirement.FactionCrimeSlot_item_requirement(
                                    id = 56, 
                                    is_reusable = True, 
                                    is_available = True, ), 
                                user = openapi_client.models.faction_crime_user.FactionCrimeUser(
                                    id = 56, 
                                    outcome = 'Successful', 
                                    joined_at = 56, 
                                    progress = 1.337, ), 
                                checkpoint_pass_rate = 56, )
                            ], 
                        rewards = openapi_client.models.faction_crime_reward.FactionCrimeReward(
                            money = 56, 
                            items = [
                                openapi_client.models.faction_crime_reward_item.FactionCrimeRewardItem(
                                    id = 56, 
                                    quantity = 56, )
                                ], 
                            respect = 56, 
                            scope = 56, 
                            payout = openapi_client.models.faction_crime_reward_payout.FactionCrimeRewardPayout(
                                type = 'balance', 
                                percentage = 56, 
                                paid_by = 56, 
                                paid_at = 56, ), ), )
                    ],
                crime = openapi_client.models.faction_crime.FactionCrime(
                    id = 56, 
                    previous_crime_id = 56, 
                    name = '', 
                    difficulty = 56, 
                    status = 'Recruiting', 
                    created_at = 56, 
                    planning_at = 56, 
                    ready_at = 56, 
                    expired_at = 56, 
                    executed_at = 56, 
                    slots = [
                        openapi_client.models.faction_crime_slot.FactionCrimeSlot(
                            position = '', 
                            position_id = 'P1', 
                            position_number = 56, 
                            item_requirement = openapi_client.models.faction_crime_slot_item_requirement.FactionCrimeSlot_item_requirement(
                                id = 56, 
                                is_reusable = True, 
                                is_available = True, ), 
                            user = openapi_client.models.faction_crime_user.FactionCrimeUser(
                                id = 56, 
                                outcome = 'Successful', 
                                joined_at = 56, 
                                progress = 1.337, ), 
                            checkpoint_pass_rate = 56, )
                        ], 
                    rewards = openapi_client.models.faction_crime_reward.FactionCrimeReward(
                        money = 56, 
                        items = [
                            openapi_client.models.faction_crime_reward_item.FactionCrimeRewardItem(
                                id = 56, 
                                quantity = 56, )
                            ], 
                        respect = 56, 
                        scope = 56, 
                        payout = openapi_client.models.faction_crime_reward_payout.FactionCrimeRewardPayout(
                            type = 'balance', 
                            percentage = 56, 
                            paid_by = 56, 
                            paid_at = 56, ), ), ),
                raids = [
                    openapi_client.models.faction_raid_warfare.FactionRaidWarfare(
                        id = 56, 
                        start = 56, 
                        end = 56, 
                        aggressor = openapi_client.models.faction_raid_warfare_faction.FactionRaidWarfareFaction(
                            id = 56, 
                            name = '', 
                            score = 1.337, 
                            chain = 56, ), 
                        defender = openapi_client.models.faction_raid_warfare_faction.FactionRaidWarfareFaction(
                            id = 56, 
                            name = '', 
                            score = 1.337, 
                            chain = 56, ), )
                    ],
                warfare = None,
                rankedwarreport = openapi_client.models.faction_ranked_war_report_response_rankedwarreport.FactionRankedWarReportResponse_rankedwarreport(
                    id = 56, 
                    start = 56, 
                    end = 56, 
                    winner = 56, 
                    forfeit = True, 
                    factions = [
                        openapi_client.models.faction_ranked_war_report_response_rankedwarreport_factions_inner.FactionRankedWarReportResponse_rankedwarreport_factions_inner(
                            id = 56, 
                            name = '', 
                            score = 56, 
                            attacks = 56, 
                            rank = openapi_client.models.faction_ranked_war_report_response_rankedwarreport_factions_inner_rank.FactionRankedWarReportResponse_rankedwarreport_factions_inner_rank(
                                before = '', 
                                after = '', ), 
                            rewards = openapi_client.models.faction_ranked_war_report_response_rankedwarreport_factions_inner_rewards.FactionRankedWarReportResponse_rankedwarreport_factions_inner_rewards(
                                respect = 56, 
                                points = 56, 
                                items = [
                                    openapi_client.models.faction_ranked_war_report_response_rankedwarreport_factions_inner_rewards_items_inner.FactionRankedWarReportResponse_rankedwarreport_factions_inner_rewards_items_inner(
                                        id = 56, 
                                        name = '', 
                                        quantity = 56, )
                                    ], ), 
                            members = [
                                openapi_client.models.faction_ranked_war_report_response_rankedwarreport_factions_inner_members_inner.FactionRankedWarReportResponse_rankedwarreport_factions_inner_members_inner(
                                    id = 56, 
                                    name = '', 
                                    level = 56, 
                                    attacks = 56, 
                                    score = 1.337, )
                                ], )
                        ], ),
                territorywarreport = [
                    openapi_client.models.faction_territory_war_report.FactionTerritoryWarReport(
                        id = 56, 
                        territory = 'AAB', 
                        started_at = 56, 
                        ended_at = 56, 
                        winner = 56, 
                        result = '', 
                        factions = [
                            openapi_client.models.faction_territory_war_report_faction.FactionTerritoryWarReportFaction(
                                id = 56, 
                                name = '', 
                                score = 56, 
                                joins = 56, 
                                clears = 56, 
                                is_aggressor = True, 
                                members = [
                                    openapi_client.models.faction_territory_war_report_members.FactionTerritoryWarReportMembers(
                                        id = 56, 
                                        username = '', 
                                        level = 56, 
                                        score = 56, 
                                        joins = 56, 
                                        clears = 56, )
                                    ], )
                            ], )
                    ],
                territory = [
                    openapi_client.models.faction_territory.FactionTerritory(
                        id = 'AAB', 
                        acquired_at = 56, 
                        sector = 56, 
                        size = 56, 
                        density = 56, 
                        slots = 56, 
                        respect = 56, 
                        coordinates = openapi_client.models.torn_territory_coordinates.TornTerritoryCoordinates(
                            x = 1.337, 
                            y = 1.337, ), 
                        racket = openapi_client.models.torn_racket.TornRacket(
                            name = '', 
                            level = 56, 
                            description = '', 
                            reward = openapi_client.models.torn_racket_reward.TornRacketReward(
                                type = 'Item', 
                                quantity = 56, 
                                id = 56, ), 
                            created_at = 56, 
                            changed_at = 56, ), )
                    ],
                upgrades = openapi_client.models.faction_upgrades.FactionUpgrades(
                    core = openapi_client.models.faction_upgrades_core.FactionUpgrades_core(), 
                    peace = [
                        openapi_client.models.faction_branch_details.FactionBranchDetails(
                            name = '', 
                            order = 56, 
                            multiplier = 56, 
                            upgrades = [
                                openapi_client.models.faction_upgrade_details.FactionUpgradeDetails(
                                    id = 56, 
                                    name = '', 
                                    ability = '', 
                                    level = 56, 
                                    cost = 56, 
                                    unlocked_at = 56, )
                                ], )
                        ], 
                    war = [
                        openapi_client.models.faction_branch_details.FactionBranchDetails(
                            name = '', 
                            order = 56, 
                            multiplier = 56, 
                            upgrades = [
                                openapi_client.models.faction_upgrade_details.FactionUpgradeDetails(
                                    id = 56, 
                                    name = '', 
                                    ability = '', 
                                    level = 56, 
                                    cost = 56, 
                                    unlocked_at = 56, )
                                ], )
                        ], ),
                state = 'war',
                stats = [
                    openapi_client.models.faction_stat.FactionStat(
                        name = 'medicalitemsused', 
                        value = 56, )
                    ],
                contributors = [
                    openapi_client.models.faction_contributor.FactionContributor(
                        id = 56, 
                        username = '', 
                        value = 56, 
                        in_faction = True, )
                    ],
                rackets = [
                    openapi_client.models.torn_racket.TornRacket(
                        name = '', 
                        level = 56, 
                        description = '', 
                        reward = openapi_client.models.torn_racket_reward.TornRacketReward(
                            type = 'Item', 
                            quantity = 56, 
                            id = 56, ), 
                        created_at = 56, 
                        changed_at = 56, )
                    ],
                rankedwars = [
                    openapi_client.models.faction_ranked_war_details.FactionRankedWarDetails(
                        id = 56, 
                        start = 56, 
                        end = 56, 
                        target = 56, 
                        winner = 56, 
                        factions = [
                            openapi_client.models.faction_ranked_war_details_factions_inner.FactionRankedWarDetails_factions_inner(
                                id = 56, 
                                name = '', 
                                score = 56, 
                                chain = 56, )
                            ], )
                    ],
                selections = [
                    null
                    ],
                timestamp = 56
            )
        else:
            return Dd89e28b1f1ed88853b09ecc982e4e66200Response(
                hof = openapi_client.models.faction_hof_stats.FactionHofStats(
                    rank = openapi_client.models.hof_value_string.HofValueString(
                        value = '', 
                        rank = 56, ), 
                    respect = openapi_client.models.hof_value.HofValue(
                        value = 56, 
                        rank = 56, ), 
                    chain = openapi_client.models.hof_value.HofValue(
                        value = 56, 
                        rank = 56, ), ),
                members = [
                    openapi_client.models.faction_member.FactionMember(
                        id = 56, 
                        name = '', 
                        position = '', 
                        level = 56, 
                        days_in_faction = 56, 
                        is_revivable = True, 
                        is_on_wall = True, 
                        is_in_oc = True, 
                        has_early_discharge = True, 
                        last_action = openapi_client.models.user_last_action.UserLastAction(
                            status = '', 
                            timestamp = 56, 
                            relative = '', ), 
                        status = openapi_client.models.user_status.UserStatus(
                            description = '', 
                            details = '', 
                            state = '', 
                            until = 56, ), 
                        revive_setting = 'Everyone', )
                    ],
                basic = openapi_client.models.faction_basic.FactionBasic(
                    id = 56, 
                    name = '', 
                    tag = '', 
                    tag_image = '', 
                    leader_id = 56, 
                    co_leader_id = 56, 
                    respect = 56, 
                    days_old = 56, 
                    capacity = 56, 
                    members = 56, 
                    is_enlisted = True, 
                    rank = openapi_client.models.faction_rank.FactionRank(
                        level = 56, 
                        name = '', 
                        division = 56, 
                        position = 56, 
                        wins = 56, ), 
                    best_chain = 56, ),
                pacts = [
                    openapi_client.models.faction_pact.FactionPact(
                        faction_id = 56, 
                        faction_name = '', 
                        until = '', )
                    ],
                wars = openapi_client.models.faction_wars.FactionWars(
                    ranked = openapi_client.models.faction_ranked_war.FactionRankedWar(
                        war_id = 56, 
                        start = 56, 
                        end = 56, 
                        target = 56, 
                        winner = 56, 
                        factions = [
                            openapi_client.models.faction_ranked_war_participant.FactionRankedWarParticipant(
                                id = 56, 
                                name = '', 
                                score = 56, 
                                chain = 56, )
                            ], ), 
                    raids = [
                        openapi_client.models.faction_raid_war.FactionRaidWar(
                            war_id = 56, 
                            start = 56, 
                            end = 56, 
                            factions = [
                                openapi_client.models.faction_raid_war_participant.FactionRaidWarParticipant(
                                    id = 56, 
                                    name = '', 
                                    score = 56, 
                                    chain = 56, 
                                    is_aggressor = True, )
                                ], )
                        ], 
                    territory = [
                        openapi_client.models.faction_territory_war.FactionTerritoryWar(
                            war_id = 56, 
                            territory = '', 
                            start = 56, 
                            end = 56, 
                            target = 56, 
                            winner = 56, 
                            factions = [
                                openapi_client.models.faction_territory_war_participant.FactionTerritoryWarParticipant(
                                    id = 56, 
                                    name = '', 
                                    score = 56, 
                                    chain = 56, 
                                    is_aggressor = True, 
                                    player_ids = [
                                        56
                                        ], )
                                ], )
                        ], ),
                news = [
                    openapi_client.models.faction_news.FactionNews(
                        id = '', 
                        text = '', 
                        timestamp = 56, )
                    ],
                metadata = openapi_client.models.request_metadata_with_links.RequestMetadataWithLinks(
                    links = openapi_client.models.request_links.RequestLinks(
                        next = '', 
                        prev = '', ), ),
                revives = [
                    openapi_client.models.revive_simplified.ReviveSimplified(
                        id = 56, 
                        reviver = openapi_client.models.revive_simplified_reviver.ReviveSimplified_reviver(
                            id = 56, 
                            faction_id = 56, ), 
                        target = openapi_client.models.revive_simplified_target.ReviveSimplified_target(
                            id = 56, 
                            faction_id = 56, 
                            hospital_reason = '', 
                            early_discharge = True, 
                            last_action = 56, 
                            online_status = '', ), 
                        success_chance = 1.337, 
                        result = '', 
                        timestamp = 56, )
                    ],
                territorywars = None,
                attacks = [
                    openapi_client.models.attack_simplified.AttackSimplified(
                        id = 56, 
                        code = '', 
                        started = 56, 
                        ended = 56, 
                        attacker = openapi_client.models.attack_player_simplified.AttackPlayerSimplified(
                            id = 56, 
                            faction_id = 56, ), 
                        defender = openapi_client.models.attack_player_simplified.AttackPlayerSimplified(
                            id = 56, 
                            faction_id = 56, ), 
                        result = 'None', 
                        respect_gain = 1.337, 
                        respect_loss = 1.337, )
                    ],
                balance = openapi_client.models.faction_balance.FactionBalance(
                    faction = openapi_client.models.faction_balance_faction.FactionBalance_faction(
                        money = 56, 
                        points = 56, 
                        scope = 56, ), 
                    members = [
                        openapi_client.models.faction_balance_members_inner.FactionBalance_members_inner(
                            id = 56, 
                            username = '', 
                            money = 56, 
                            points = 56, )
                        ], ),
                raidreport = [
                    openapi_client.models.faction_raid_report.FactionRaidReport(
                        id = 56, 
                        start = 56, 
                        end = 56, 
                        aggressor = openapi_client.models.faction_raid_report_faction.FactionRaidReportFaction(
                            id = 56, 
                            name = '', 
                            score = 1.337, 
                            attackers = [
                                openapi_client.models.faction_raid_report_attacker.FactionRaidReportAttacker(
                                    user = openapi_client.models.report_friend_or_foe_user.ReportFriendOrFoeUser(
                                        id = 56, 
                                        name = '', ), 
                                    attacks = 56, 
                                    damage = 1.337, )
                                ], 
                            non_attackers = [
                                openapi_client.models.report_friend_or_foe_user.ReportFriendOrFoeUser(
                                    id = 56, 
                                    name = '', )
                                ], ), 
                        defender = openapi_client.models.faction_raid_report_faction.FactionRaidReportFaction(
                            id = 56, 
                            name = '', 
                            score = 1.337, 
                            attackers = [
                                openapi_client.models.faction_raid_report_attacker.FactionRaidReportAttacker(
                                    user = , 
                                    attacks = 56, 
                                    damage = 1.337, )
                                ], 
                            non_attackers = [
                                
                                ], ), )
                    ],
                territory_ownership = [
                    openapi_client.models.faction_territory_ownership.FactionTerritoryOwnership(
                        id = '', 
                        owned_by = 56, 
                        acquired_at = 56, )
                    ],
                positions = [
                    openapi_client.models.faction_position.FactionPosition(
                        name = '', 
                        is_default = True, 
                        abilities = [
                            'Medical Item Usage'
                            ], )
                    ],
                applications = [
                    openapi_client.models.faction_application.FactionApplication(
                        id = 56, 
                        user = openapi_client.models.faction_application_user.FactionApplication_user(
                            id = 56, 
                            name = '', 
                            level = 56, 
                            stats = openapi_client.models.faction_application_user_stats.FactionApplication_user_stats(
                                strength = 56, 
                                speed = 56, 
                                dexterity = 56, 
                                defense = 56, ), ), 
                        message = '', 
                        valid_until = 56, 
                        status = 'accepted', )
                    ],
                chain = openapi_client.models.faction_ongoing_chain.FactionOngoingChain(
                    id = 56, 
                    current = 56, 
                    max = 56, 
                    timeout = 56, 
                    modifier = 1.337, 
                    cooldown = 56, 
                    start = 56, 
                    end = 56, ),
                chains = [
                    openapi_client.models.faction_chain.FactionChain(
                        id = 56, 
                        chain = 56, 
                        respect = 1.337, 
                        start = 56, 
                        end = 56, )
                    ],
                chainreport = openapi_client.models.faction_chain_report.FactionChainReport(
                    id = 56, 
                    faction_id = 56, 
                    start = 56, 
                    end = 56, 
                    details = openapi_client.models.faction_chain_report_details.FactionChainReportDetails(
                        chain = 56, 
                        respect = 1.337, 
                        members = 56, 
                        targets = 56, 
                        war = 56, 
                        best = 1.337, 
                        leave = 56, 
                        mug = 56, 
                        hospitalize = 56, 
                        assists = 56, 
                        retaliations = 56, 
                        overseas = 56, 
                        draws = 56, 
                        escapes = 56, 
                        losses = 56, ), 
                    bonuses = [
                        openapi_client.models.faction_chain_report_bonus.FactionChainReportBonus(
                            attacker_id = 56, 
                            defender_id = 56, 
                            chain = 56, 
                            respect = 56, )
                        ], 
                    attackers = [
                        openapi_client.models.faction_chain_report_attacker.FactionChainReportAttacker(
                            id = 56, 
                            respect = openapi_client.models.faction_chain_report_attacker_respect.FactionChainReportAttackerRespect(
                                total = 1.337, 
                                average = 1.337, 
                                best = 1.337, ), 
                            attacks = openapi_client.models.faction_chain_report_attacker_attacks.FactionChainReportAttackerAttacks(
                                total = 56, 
                                leave = 56, 
                                mug = 56, 
                                hospitalize = 56, 
                                assists = 56, 
                                retaliations = 56, 
                                overseas = 56, 
                                draws = 56, 
                                escapes = 56, 
                                losses = 56, 
                                war = 56, 
                                bonuses = 56, ), )
                        ], 
                    non_attackers = [
                        56
                        ], ),
                crimes = [
                    openapi_client.models.faction_crime.FactionCrime(
                        id = 56, 
                        previous_crime_id = 56, 
                        name = '', 
                        difficulty = 56, 
                        status = 'Recruiting', 
                        created_at = 56, 
                        planning_at = 56, 
                        ready_at = 56, 
                        expired_at = 56, 
                        executed_at = 56, 
                        slots = [
                            openapi_client.models.faction_crime_slot.FactionCrimeSlot(
                                position = '', 
                                position_id = 'P1', 
                                position_number = 56, 
                                item_requirement = openapi_client.models.faction_crime_slot_item_requirement.FactionCrimeSlot_item_requirement(
                                    id = 56, 
                                    is_reusable = True, 
                                    is_available = True, ), 
                                user = openapi_client.models.faction_crime_user.FactionCrimeUser(
                                    id = 56, 
                                    outcome = 'Successful', 
                                    joined_at = 56, 
                                    progress = 1.337, ), 
                                checkpoint_pass_rate = 56, )
                            ], 
                        rewards = openapi_client.models.faction_crime_reward.FactionCrimeReward(
                            money = 56, 
                            items = [
                                openapi_client.models.faction_crime_reward_item.FactionCrimeRewardItem(
                                    id = 56, 
                                    quantity = 56, )
                                ], 
                            respect = 56, 
                            scope = 56, 
                            payout = openapi_client.models.faction_crime_reward_payout.FactionCrimeRewardPayout(
                                type = 'balance', 
                                percentage = 56, 
                                paid_by = 56, 
                                paid_at = 56, ), ), )
                    ],
                crime = openapi_client.models.faction_crime.FactionCrime(
                    id = 56, 
                    previous_crime_id = 56, 
                    name = '', 
                    difficulty = 56, 
                    status = 'Recruiting', 
                    created_at = 56, 
                    planning_at = 56, 
                    ready_at = 56, 
                    expired_at = 56, 
                    executed_at = 56, 
                    slots = [
                        openapi_client.models.faction_crime_slot.FactionCrimeSlot(
                            position = '', 
                            position_id = 'P1', 
                            position_number = 56, 
                            item_requirement = openapi_client.models.faction_crime_slot_item_requirement.FactionCrimeSlot_item_requirement(
                                id = 56, 
                                is_reusable = True, 
                                is_available = True, ), 
                            user = openapi_client.models.faction_crime_user.FactionCrimeUser(
                                id = 56, 
                                outcome = 'Successful', 
                                joined_at = 56, 
                                progress = 1.337, ), 
                            checkpoint_pass_rate = 56, )
                        ], 
                    rewards = openapi_client.models.faction_crime_reward.FactionCrimeReward(
                        money = 56, 
                        items = [
                            openapi_client.models.faction_crime_reward_item.FactionCrimeRewardItem(
                                id = 56, 
                                quantity = 56, )
                            ], 
                        respect = 56, 
                        scope = 56, 
                        payout = openapi_client.models.faction_crime_reward_payout.FactionCrimeRewardPayout(
                            type = 'balance', 
                            percentage = 56, 
                            paid_by = 56, 
                            paid_at = 56, ), ), ),
                raids = [
                    openapi_client.models.faction_raid_warfare.FactionRaidWarfare(
                        id = 56, 
                        start = 56, 
                        end = 56, 
                        aggressor = openapi_client.models.faction_raid_warfare_faction.FactionRaidWarfareFaction(
                            id = 56, 
                            name = '', 
                            score = 1.337, 
                            chain = 56, ), 
                        defender = openapi_client.models.faction_raid_warfare_faction.FactionRaidWarfareFaction(
                            id = 56, 
                            name = '', 
                            score = 1.337, 
                            chain = 56, ), )
                    ],
                warfare = None,
                rankedwarreport = openapi_client.models.faction_ranked_war_report_response_rankedwarreport.FactionRankedWarReportResponse_rankedwarreport(
                    id = 56, 
                    start = 56, 
                    end = 56, 
                    winner = 56, 
                    forfeit = True, 
                    factions = [
                        openapi_client.models.faction_ranked_war_report_response_rankedwarreport_factions_inner.FactionRankedWarReportResponse_rankedwarreport_factions_inner(
                            id = 56, 
                            name = '', 
                            score = 56, 
                            attacks = 56, 
                            rank = openapi_client.models.faction_ranked_war_report_response_rankedwarreport_factions_inner_rank.FactionRankedWarReportResponse_rankedwarreport_factions_inner_rank(
                                before = '', 
                                after = '', ), 
                            rewards = openapi_client.models.faction_ranked_war_report_response_rankedwarreport_factions_inner_rewards.FactionRankedWarReportResponse_rankedwarreport_factions_inner_rewards(
                                respect = 56, 
                                points = 56, 
                                items = [
                                    openapi_client.models.faction_ranked_war_report_response_rankedwarreport_factions_inner_rewards_items_inner.FactionRankedWarReportResponse_rankedwarreport_factions_inner_rewards_items_inner(
                                        id = 56, 
                                        name = '', 
                                        quantity = 56, )
                                    ], ), 
                            members = [
                                openapi_client.models.faction_ranked_war_report_response_rankedwarreport_factions_inner_members_inner.FactionRankedWarReportResponse_rankedwarreport_factions_inner_members_inner(
                                    id = 56, 
                                    name = '', 
                                    level = 56, 
                                    attacks = 56, 
                                    score = 1.337, )
                                ], )
                        ], ),
                territorywarreport = [
                    openapi_client.models.faction_territory_war_report.FactionTerritoryWarReport(
                        id = 56, 
                        territory = 'AAB', 
                        started_at = 56, 
                        ended_at = 56, 
                        winner = 56, 
                        result = '', 
                        factions = [
                            openapi_client.models.faction_territory_war_report_faction.FactionTerritoryWarReportFaction(
                                id = 56, 
                                name = '', 
                                score = 56, 
                                joins = 56, 
                                clears = 56, 
                                is_aggressor = True, 
                                members = [
                                    openapi_client.models.faction_territory_war_report_members.FactionTerritoryWarReportMembers(
                                        id = 56, 
                                        username = '', 
                                        level = 56, 
                                        score = 56, 
                                        joins = 56, 
                                        clears = 56, )
                                    ], )
                            ], )
                    ],
                territory = [
                    openapi_client.models.faction_territory.FactionTerritory(
                        id = 'AAB', 
                        acquired_at = 56, 
                        sector = 56, 
                        size = 56, 
                        density = 56, 
                        slots = 56, 
                        respect = 56, 
                        coordinates = openapi_client.models.torn_territory_coordinates.TornTerritoryCoordinates(
                            x = 1.337, 
                            y = 1.337, ), 
                        racket = openapi_client.models.torn_racket.TornRacket(
                            name = '', 
                            level = 56, 
                            description = '', 
                            reward = openapi_client.models.torn_racket_reward.TornRacketReward(
                                type = 'Item', 
                                quantity = 56, 
                                id = 56, ), 
                            created_at = 56, 
                            changed_at = 56, ), )
                    ],
                upgrades = openapi_client.models.faction_upgrades.FactionUpgrades(
                    core = openapi_client.models.faction_upgrades_core.FactionUpgrades_core(), 
                    peace = [
                        openapi_client.models.faction_branch_details.FactionBranchDetails(
                            name = '', 
                            order = 56, 
                            multiplier = 56, 
                            upgrades = [
                                openapi_client.models.faction_upgrade_details.FactionUpgradeDetails(
                                    id = 56, 
                                    name = '', 
                                    ability = '', 
                                    level = 56, 
                                    cost = 56, 
                                    unlocked_at = 56, )
                                ], )
                        ], 
                    war = [
                        openapi_client.models.faction_branch_details.FactionBranchDetails(
                            name = '', 
                            order = 56, 
                            multiplier = 56, 
                            upgrades = [
                                openapi_client.models.faction_upgrade_details.FactionUpgradeDetails(
                                    id = 56, 
                                    name = '', 
                                    ability = '', 
                                    level = 56, 
                                    cost = 56, 
                                    unlocked_at = 56, )
                                ], )
                        ], ),
                state = 'war',
                stats = [
                    openapi_client.models.faction_stat.FactionStat(
                        name = 'medicalitemsused', 
                        value = 56, )
                    ],
                contributors = [
                    openapi_client.models.faction_contributor.FactionContributor(
                        id = 56, 
                        username = '', 
                        value = 56, 
                        in_faction = True, )
                    ],
                rackets = [
                    openapi_client.models.torn_racket.TornRacket(
                        name = '', 
                        level = 56, 
                        description = '', 
                        reward = openapi_client.models.torn_racket_reward.TornRacketReward(
                            type = 'Item', 
                            quantity = 56, 
                            id = 56, ), 
                        created_at = 56, 
                        changed_at = 56, )
                    ],
                rankedwars = [
                    openapi_client.models.faction_ranked_war_details.FactionRankedWarDetails(
                        id = 56, 
                        start = 56, 
                        end = 56, 
                        target = 56, 
                        winner = 56, 
                        factions = [
                            openapi_client.models.faction_ranked_war_details_factions_inner.FactionRankedWarDetails_factions_inner(
                                id = 56, 
                                name = '', 
                                score = 56, 
                                chain = 56, )
                            ], )
                    ],
                selections = [
                    null
                    ],
                timestamp = 56,
        )
        """

    def testDd89e28b1f1ed88853b09ecc982e4e66200Response(self):
        """Test Dd89e28b1f1ed88853b09ecc982e4e66200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
