# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.torn_api import TornApi


class TestTornApi(unittest.TestCase):
    """TornApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TornApi()

    def tearDown(self) -> None:
        pass

    def test_a4fedadcac3aada40131288e4e3d6c2d(self) -> None:
        """Test case for a4fedadcac3aada40131288e4e3d6c2d

        Get information about items
        """
        pass

    def test_ad45b0f57a1109977f605581fc294bda(self) -> None:
        """Test case for ad45b0f57a1109977f605581fc294bda

        Get Subcrimes information
        """
        pass

    def test_b64b8cf22cd9e9c8916bc01439f6b069(self) -> None:
        """Test case for b64b8cf22cd9e9c8916bc01439f6b069

        Get organized crimes information
        """
        pass

    def test_b73ff4e5a9dd28905060da24ca76efde(self) -> None:
        """Test case for b73ff4e5a9dd28905060da24ca76efde

        Get crimes information
        """
        pass

    def test_c44f572f4672071280a28e6f8217c3b6(self) -> None:
        """Test case for c44f572f4672071280a28e6f8217c3b6

        Get properties details
        """
        pass

    def test_call_0f4c4c07e1dfacbda689b2a0d62ccda4(self) -> None:
        """Test case for call_0f4c4c07e1dfacbda689b2a0d62ccda4

        Get information about items
        """
        pass

    def test_call_1846c4cf1e6878553e36571dc9cac29f(self) -> None:
        """Test case for call_1846c4cf1e6878553e36571dc9cac29f

        Get any Torn selection
        """
        pass

    def test_call_279e811630fa497fb2cae268c70992e2(self) -> None:
        """Test case for call_279e811630fa497fb2cae268c70992e2

        Get bounties
        """
        pass

    def test_call_2a67e4b84813ee97a398be48e544abf5(self) -> None:
        """Test case for call_2a67e4b84813ee97a398be48e544abf5

        Get faction hall of fame positions for a specific category
        """
        pass

    def test_call_2baae03f953cd57fd5303dd1d04efae0(self) -> None:
        """Test case for call_2baae03f953cd57fd5303dd1d04efae0

        Get all available torn selections
        """
        pass

    def test_call_2e799e84fcfa9b722f856e859df909f8(self) -> None:
        """Test case for call_2e799e84fcfa9b722f856e859df909f8

        Get information about ammo
        """
        pass

    def test_call_2f68d7e04d218e26005be3eeca6de583(self) -> None:
        """Test case for call_2f68d7e04d218e26005be3eeca6de583

        Get available log categories
        """
        pass

    def test_call_37f1828422f3080da21f9eb4aa576686(self) -> None:
        """Test case for call_37f1828422f3080da21f9eb4aa576686

        Get territory details
        """
        pass

    def test_call_61c2d0bc6980cf8d730fe48eb81f417b(self) -> None:
        """Test case for call_61c2d0bc6980cf8d730fe48eb81f417b

        Get attack log details
        """
        pass

    def test_call_6f8cffcdae9fe97110b8d46c3991f109(self) -> None:
        """Test case for call_6f8cffcdae9fe97110b8d46c3991f109

        Get current server time
        """
        pass

    def test_call_7be904fbcb98a7bb724f0c5b02a37a25(self) -> None:
        """Test case for call_7be904fbcb98a7bb724f0c5b02a37a25

        Get available log ids for a specific log category
        """
        pass

    def test_call_80ad6ebd50b6c075427c04d2f54d7af5(self) -> None:
        """Test case for call_80ad6ebd50b6c075427c04d2f54d7af5

        Get information about weapon upgrades
        """
        pass

    def test_call_911d56b49218cef2102be3de73f82f01(self) -> None:
        """Test case for call_911d56b49218cef2102be3de73f82f01

        Get player hall of fame positions for a specific category
        """
        pass

    def test_call_992f8b71435ca78ba96f1e5298c25152(self) -> None:
        """Test case for call_992f8b71435ca78ba96f1e5298c25152

        Get education information
        """
        pass

    def test_d4cb87bc2502a517c49525b910a6dd82(self) -> None:
        """Test case for d4cb87bc2502a517c49525b910a6dd82

        Get all available log ids
        """
        pass

    def test_e95c96ef528248341647a5704630320e(self) -> None:
        """Test case for e95c96ef528248341647a5704630320e

        Get calendar information
        """
        pass

    def test_f45431b364546bb20b0ca909e9ac686e(self) -> None:
        """Test case for f45431b364546bb20b0ca909e9ac686e

        Get full faction tree
        """
        pass


if __name__ == '__main__':
    unittest.main()
