# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_a72308321da0c4a2c31c60218acc7a85(self) -> None:
        """Test case for a72308321da0c4a2c31c60218acc7a85

        Get current server time
        """
        pass

    def test_b7ebbeea51dc2ef56c3ed5fd9d94e680(self) -> None:
        """Test case for b7ebbeea51dc2ef56c3ed5fd9d94e680

        Get your current faction balance
        """
        pass

    def test_ba6e495bf0c6b2e87db337c1a09f4852(self) -> None:
        """Test case for ba6e495bf0c6b2e87db337c1a09f4852

        Get user races
        """
        pass

    def test_c0a6c91697cd1683c39b3c0649a18ec8(self) -> None:
        """Test case for c0a6c91697cd1683c39b3c0649a18ec8

        Get all available user selections
        """
        pass

    def test_c85fd102a25aaec3aa98611d0da6c219(self) -> None:
        """Test case for c85fd102a25aaec3aa98611d0da6c219

        Get bounties placed on you
        """
        pass

    def test_call_0452cb8fd031b80d3b7e9fcb7b0bdf09(self) -> None:
        """Test case for call_0452cb8fd031b80d3b7e9fcb7b0bdf09

        Get your current property
        """
        pass

    def test_call_17f99b99fac9601887dd1d001b95bb08(self) -> None:
        """Test case for call_17f99b99fac9601887dd1d001b95bb08

        Get updates on your threads and posts
        """
        pass

    def test_call_2ceb7f08dc5f06a01d1fbe50425414c1(self) -> None:
        """Test case for call_2ceb7f08dc5f06a01d1fbe50425414c1

        Get updates on your friends' activity
        """
        pass

    def test_call_37f1e394f9d6e3f6fd436fae3e9b9ac4(self) -> None:
        """Test case for call_37f1e394f9d6e3f6fd436fae3e9b9ac4

        Get your crime statistics
        """
        pass

    def test_call_388e8008ae1c2645819af76d71ef92a5(self) -> None:
        """Test case for call_388e8008ae1c2645819af76d71ef92a5

        Get your personal stats
        """
        pass

    def test_call_3acc98a3016974b786cb01e04e1ced04(self) -> None:
        """Test case for call_3acc98a3016974b786cb01e04e1ced04

        Get your detailed attacks
        """
        pass

    def test_call_3c6f8acbfcb398592e3f3b65ab91a40f(self) -> None:
        """Test case for call_3c6f8acbfcb398592e3f3b65ab91a40f

        Get your current ongoing organized crime
        """
        pass

    def test_call_3c847eb1325040798f37a7492108e094(self) -> None:
        """Test case for call_3c847eb1325040798f37a7492108e094

        Get your detailed revives
        """
        pass

    def test_call_423ceffcad89f9ee7abfb85bed32b692(self) -> None:
        """Test case for call_423ceffcad89f9ee7abfb85bed32b692

        Get posts for a specific player
        """
        pass

    def test_call_481c6645dae298b54f0630ef7de81dba(self) -> None:
        """Test case for call_481c6645dae298b54f0630ef7de81dba

        Get threads for a specific player
        """
        pass

    def test_call_4cc4cc6fa3764f9732db9589e91d7739(self) -> None:
        """Test case for call_4cc4cc6fa3764f9732db9589e91d7739

        Get your competition's event start time
        """
        pass

    def test_call_574a416ca46717830f03a2f685955b87(self) -> None:
        """Test case for call_574a416ca46717830f03a2f685955b87

        Get your own properties
        """
        pass

    def test_call_601f7b38ac25e1ac47b33fb64120198b(self) -> None:
        """Test case for call_601f7b38ac25e1ac47b33fb64120198b

        Get specific user's properties
        """
        pass

    def test_call_6ac851069df2c33e53cc69eecae44f1e(self) -> None:
        """Test case for call_6ac851069df2c33e53cc69eecae44f1e

        Get a player's personal stats
        """
        pass

    def test_call_6ba15a813fe1cc014564e9dba892e022(self) -> None:
        """Test case for call_6ba15a813fe1cc014564e9dba892e022

        Get your reports
        """
        pass

    def test_call_807adc6a64d86e07d629a15dde8c6105(self) -> None:
        """Test case for call_807adc6a64d86e07d629a15dde8c6105

        Get your threads
        """
        pass

    def test_call_8820cd889afde899353037ca5a0f9a07(self) -> None:
        """Test case for call_8820cd889afde899353037ca5a0f9a07

        Get your simplified revives
        """
        pass

    def test_call_8fcbe4dcf8a3a28e31e2eaab877feea1(self) -> None:
        """Test case for call_8fcbe4dcf8a3a28e31e2eaab877feea1

        Get your item market listings for a specific item
        """
        pass

    def test_call_92c7e86065c3d18b000e825aa6688eed(self) -> None:
        """Test case for call_92c7e86065c3d18b000e825aa6688eed

        Get updates on threads you subscribed to
        """
        pass

    def test_call_959a3a302d736b416ec1edd4def8fe91(self) -> None:
        """Test case for call_959a3a302d736b416ec1edd4def8fe91

        Get your hall of fame rankings
        """
        pass

    def test_cc3a21ed98c1a80ffeeda4e33c75b9a0(self) -> None:
        """Test case for cc3a21ed98c1a80ffeeda4e33c75b9a0

        Get your posts
        """
        pass

    def test_ce480599312126b8a5d77ced3ab8caa8(self) -> None:
        """Test case for ce480599312126b8a5d77ced3ab8caa8

        Get any User selection
        """
        pass

    def test_dc3deee7629610931240be337c47a8ee(self) -> None:
        """Test case for dc3deee7629610931240be337c47a8ee

        Get user enlisted cars
        """
        pass

    def test_e1b2c1039ea41f7607b9c94660fc72cb(self) -> None:
        """Test case for e1b2c1039ea41f7607b9c94660fc72cb

        Get your current racing records
        """
        pass

    def test_e93ba44fcc7ad2eb3063dec7469ee2f6(self) -> None:
        """Test case for e93ba44fcc7ad2eb3063dec7469ee2f6

        Get your friends, enemies or targets list
        """
        pass

    def test_e995691fd9845c8b4a91f065ac9c8420(self) -> None:
        """Test case for e995691fd9845c8b4a91f065ac9c8420

        Get your simplified attacks
        """
        pass

    def test_eb5eca5c6b978ee23ef74035c14ff4cc(self) -> None:
        """Test case for eb5eca5c6b978ee23ef74035c14ff4cc

        Get bounties placed on a specific user
        """
        pass

    def test_f36ce18449194dd9d2b62bccd4bb8343(self) -> None:
        """Test case for f36ce18449194dd9d2b62bccd4bb8343

        Get specific user's property
        """
        pass

    def test_f86d41c9434e42d22f9ff46ecc4e5b88(self) -> None:
        """Test case for f86d41c9434e42d22f9ff46ecc4e5b88

        Get hall of fame rankings for a specific player
        """
        pass

    def test_facf1ddeef80a440229941f49aec6ccc(self) -> None:
        """Test case for facf1ddeef80a440229941f49aec6ccc

        Get your starter job positions
        """
        pass

    def test_fddc6adc5139d8a1e0a151d80816dba7(self) -> None:
        """Test case for fddc6adc5139d8a1e0a151d80816dba7

        Get your education information
        """
        pass


if __name__ == '__main__':
    unittest.main()
