# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.faction_territory_warfare import FactionTerritoryWarfare

class TestFactionTerritoryWarfare(unittest.TestCase):
    """FactionTerritoryWarfare unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FactionTerritoryWarfare:
        """Test FactionTerritoryWarfare
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FactionTerritoryWarfare`
        """
        model = FactionTerritoryWarfare()
        if include_optional:
            return FactionTerritoryWarfare(
                id = 56,
                territory = 'AAB',
                start = 56,
                end = 56,
                target = 56,
                aggressor = openapi_client.models.faction_territory_war_faction.FactionTerritoryWarFaction(
                    id = 56, 
                    name = '', 
                    score = 56, 
                    chain = 56, 
                    players_on_wall = [
                        openapi_client.models.report_friend_or_foe_user.ReportFriendOrFoeUser(
                            id = 56, 
                            name = '', )
                        ], ),
                defender = openapi_client.models.faction_territory_war_faction.FactionTerritoryWarFaction(
                    id = 56, 
                    name = '', 
                    score = 56, 
                    chain = 56, 
                    players_on_wall = [
                        openapi_client.models.report_friend_or_foe_user.ReportFriendOrFoeUser(
                            id = 56, 
                            name = '', )
                        ], ),
                result = ''
            )
        else:
            return FactionTerritoryWarfare(
                id = 56,
                territory = 'AAB',
                start = 56,
                end = 56,
                target = 56,
                aggressor = openapi_client.models.faction_territory_war_faction.FactionTerritoryWarFaction(
                    id = 56, 
                    name = '', 
                    score = 56, 
                    chain = 56, 
                    players_on_wall = [
                        openapi_client.models.report_friend_or_foe_user.ReportFriendOrFoeUser(
                            id = 56, 
                            name = '', )
                        ], ),
                defender = openapi_client.models.faction_territory_war_faction.FactionTerritoryWarFaction(
                    id = 56, 
                    name = '', 
                    score = 56, 
                    chain = 56, 
                    players_on_wall = [
                        openapi_client.models.report_friend_or_foe_user.ReportFriendOrFoeUser(
                            id = 56, 
                            name = '', )
                        ], ),
                result = '',
        )
        """

    def testFactionTerritoryWarfare(self):
        """Test FactionTerritoryWarfare"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
