# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.faction_news_category import FactionNewsCategory
from openapi_client.models.faction_ranked_wars_category_enum import FactionRankedWarsCategoryEnum
from openapi_client.models.faction_territory_wars_category_enum import FactionTerritoryWarsCategoryEnum
from openapi_client.models.faction_warfare_type_enum import FactionWarfareTypeEnum
from openapi_client.models.report_type_enum import ReportTypeEnum
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

DD89E28B1F1ED88853B09ECC982E4E66CATPARAMETER_ONE_OF_SCHEMAS = ["FactionNewsCategory", "FactionRankedWarsCategoryEnum", "FactionTerritoryWarsCategoryEnum", "FactionWarfareTypeEnum", "ReportTypeEnum", "str"]

class Dd89e28b1f1ed88853b09ecc982e4e66CatParameter(BaseModel):
    """
    Dd89e28b1f1ed88853b09ecc982e4e66CatParameter
    """
    # data type: str
    oneof_schema_1_validator: Optional[StrictStr] = None
    # data type: str
    oneof_schema_2_validator: Optional[StrictStr] = None
    # data type: FactionNewsCategory
    oneof_schema_3_validator: Optional[FactionNewsCategory] = None
    # data type: FactionRankedWarsCategoryEnum
    oneof_schema_4_validator: Optional[FactionRankedWarsCategoryEnum] = None
    # data type: ReportTypeEnum
    oneof_schema_5_validator: Optional[ReportTypeEnum] = None
    # data type: FactionWarfareTypeEnum
    oneof_schema_6_validator: Optional[FactionWarfareTypeEnum] = None
    # data type: FactionTerritoryWarsCategoryEnum
    oneof_schema_7_validator: Optional[FactionTerritoryWarsCategoryEnum] = None
    actual_instance: Optional[Union[FactionNewsCategory, FactionRankedWarsCategoryEnum, FactionTerritoryWarsCategoryEnum, FactionWarfareTypeEnum, ReportTypeEnum, str]] = None
    one_of_schemas: Set[str] = { "FactionNewsCategory", "FactionRankedWarsCategoryEnum", "FactionTerritoryWarsCategoryEnum", "FactionWarfareTypeEnum", "ReportTypeEnum", "str" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = Dd89e28b1f1ed88853b09ecc982e4e66CatParameter.model_construct()
        error_messages = []
        match = 0
        # validate data type: str
        try:
            instance.oneof_schema_1_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: str
        try:
            instance.oneof_schema_2_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: FactionNewsCategory
        if not isinstance(v, FactionNewsCategory):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FactionNewsCategory`")
        else:
            match += 1
        # validate data type: FactionRankedWarsCategoryEnum
        if not isinstance(v, FactionRankedWarsCategoryEnum):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FactionRankedWarsCategoryEnum`")
        else:
            match += 1
        # validate data type: ReportTypeEnum
        if not isinstance(v, ReportTypeEnum):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReportTypeEnum`")
        else:
            match += 1
        # validate data type: FactionWarfareTypeEnum
        if not isinstance(v, FactionWarfareTypeEnum):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FactionWarfareTypeEnum`")
        else:
            match += 1
        # validate data type: FactionTerritoryWarsCategoryEnum
        if not isinstance(v, FactionTerritoryWarsCategoryEnum):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FactionTerritoryWarsCategoryEnum`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in Dd89e28b1f1ed88853b09ecc982e4e66CatParameter with oneOf schemas: FactionNewsCategory, FactionRankedWarsCategoryEnum, FactionTerritoryWarsCategoryEnum, FactionWarfareTypeEnum, ReportTypeEnum, str. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in Dd89e28b1f1ed88853b09ecc982e4e66CatParameter with oneOf schemas: FactionNewsCategory, FactionRankedWarsCategoryEnum, FactionTerritoryWarsCategoryEnum, FactionWarfareTypeEnum, ReportTypeEnum, str. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into str
        try:
            # validation
            instance.oneof_schema_1_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_1_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into str
        try:
            # validation
            instance.oneof_schema_2_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_2_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FactionNewsCategory
        try:
            instance.actual_instance = FactionNewsCategory.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FactionRankedWarsCategoryEnum
        try:
            instance.actual_instance = FactionRankedWarsCategoryEnum.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReportTypeEnum
        try:
            instance.actual_instance = ReportTypeEnum.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FactionWarfareTypeEnum
        try:
            instance.actual_instance = FactionWarfareTypeEnum.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FactionTerritoryWarsCategoryEnum
        try:
            instance.actual_instance = FactionTerritoryWarsCategoryEnum.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into Dd89e28b1f1ed88853b09ecc982e4e66CatParameter with oneOf schemas: FactionNewsCategory, FactionRankedWarsCategoryEnum, FactionTerritoryWarsCategoryEnum, FactionWarfareTypeEnum, ReportTypeEnum, str. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Dd89e28b1f1ed88853b09ecc982e4e66CatParameter with oneOf schemas: FactionNewsCategory, FactionRankedWarsCategoryEnum, FactionTerritoryWarsCategoryEnum, FactionWarfareTypeEnum, ReportTypeEnum, str. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], FactionNewsCategory, FactionRankedWarsCategoryEnum, FactionTerritoryWarsCategoryEnum, FactionWarfareTypeEnum, ReportTypeEnum, str]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


