# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.faction_search_leader import FactionSearchLeader
from typing import Optional, Set
from typing_extensions import Self

class FactionSearch(BaseModel):
    """
    FactionSearch
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    respect: StrictInt
    members: StrictInt
    leader: FactionSearchLeader
    co_leader: Optional[FactionSearchLeader]
    image: Optional[StrictStr]
    tag_image: Optional[StrictStr]
    tag: Optional[StrictStr]
    is_destroyed: StrictBool
    is_recruiting: StrictBool
    __properties: ClassVar[List[str]] = ["id", "name", "respect", "members", "leader", "co_leader", "image", "tag_image", "tag", "is_destroyed", "is_recruiting"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FactionSearch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of leader
        if self.leader:
            _dict['leader'] = self.leader.to_dict()
        # override the default output from pydantic by calling `to_dict()` of co_leader
        if self.co_leader:
            _dict['co_leader'] = self.co_leader.to_dict()
        # set to None if co_leader (nullable) is None
        # and model_fields_set contains the field
        if self.co_leader is None and "co_leader" in self.model_fields_set:
            _dict['co_leader'] = None

        # set to None if image (nullable) is None
        # and model_fields_set contains the field
        if self.image is None and "image" in self.model_fields_set:
            _dict['image'] = None

        # set to None if tag_image (nullable) is None
        # and model_fields_set contains the field
        if self.tag_image is None and "tag_image" in self.model_fields_set:
            _dict['tag_image'] = None

        # set to None if tag (nullable) is None
        # and model_fields_set contains the field
        if self.tag is None and "tag" in self.model_fields_set:
            _dict['tag'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FactionSearch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "respect": obj.get("respect"),
            "members": obj.get("members"),
            "leader": FactionSearchLeader.from_dict(obj["leader"]) if obj.get("leader") is not None else None,
            "co_leader": FactionSearchLeader.from_dict(obj["co_leader"]) if obj.get("co_leader") is not None else None,
            "image": obj.get("image"),
            "tag_image": obj.get("tag_image"),
            "tag": obj.get("tag"),
            "is_destroyed": obj.get("is_destroyed"),
            "is_recruiting": obj.get("is_recruiting")
        })
        return _obj


