# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from openapi_client.models.property_lookup_response import PropertyLookupResponse
from openapi_client.models.timestamp_response import TimestampResponse
from openapi_client.models.user_property_response import UserPropertyResponse
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

MODEL2A45B6D9D77224D9A1E13D0B698F6C4B200RESPONSE_ANY_OF_SCHEMAS = ["PropertyLookupResponse", "TimestampResponse", "UserPropertyResponse"]

class Model2a45b6d9d77224d9a1e13d0b698f6c4b200Response(BaseModel):
    """
    Model2a45b6d9d77224d9a1e13d0b698f6c4b200Response
    """

    # data type: UserPropertyResponse
    anyof_schema_1_validator: Optional[UserPropertyResponse] = None
    # data type: PropertyLookupResponse
    anyof_schema_2_validator: Optional[PropertyLookupResponse] = None
    # data type: TimestampResponse
    anyof_schema_3_validator: Optional[TimestampResponse] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[PropertyLookupResponse, TimestampResponse, UserPropertyResponse]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "PropertyLookupResponse", "TimestampResponse", "UserPropertyResponse" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = Model2a45b6d9d77224d9a1e13d0b698f6c4b200Response.model_construct()
        error_messages = []
        # validate data type: UserPropertyResponse
        if not isinstance(v, UserPropertyResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UserPropertyResponse`")
        else:
            return v

        # validate data type: PropertyLookupResponse
        if not isinstance(v, PropertyLookupResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PropertyLookupResponse`")
        else:
            return v

        # validate data type: TimestampResponse
        if not isinstance(v, TimestampResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TimestampResponse`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in Model2a45b6d9d77224d9a1e13d0b698f6c4b200Response with anyOf schemas: PropertyLookupResponse, TimestampResponse, UserPropertyResponse. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[UserPropertyResponse] = None
        try:
            instance.actual_instance = UserPropertyResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[PropertyLookupResponse] = None
        try:
            instance.actual_instance = PropertyLookupResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[TimestampResponse] = None
        try:
            instance.actual_instance = TimestampResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Model2a45b6d9d77224d9a1e13d0b698f6c4b200Response with anyOf schemas: PropertyLookupResponse, TimestampResponse, UserPropertyResponse. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], PropertyLookupResponse, TimestampResponse, UserPropertyResponse]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


