# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from openapi_client.models.bazaar_response import BazaarResponse
from openapi_client.models.bazaar_response_specialized import BazaarResponseSpecialized
from openapi_client.models.market_item_market_response import MarketItemMarketResponse
from openapi_client.models.market_lookup_response import MarketLookupResponse
from openapi_client.models.market_properties_response import MarketPropertiesResponse
from openapi_client.models.market_rentals_response import MarketRentalsResponse
from openapi_client.models.timestamp_response import TimestampResponse
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

MODEL8E78BE3FA3D353F59F8654FCC1C2199C200RESPONSE_ANY_OF_SCHEMAS = ["BazaarResponse", "BazaarResponseSpecialized", "MarketItemMarketResponse", "MarketLookupResponse", "MarketPropertiesResponse", "MarketRentalsResponse", "TimestampResponse"]

class Model8e78be3fa3d353f59f8654fcc1c2199c200Response(BaseModel):
    """
    Model8e78be3fa3d353f59f8654fcc1c2199c200Response
    """

    # data type: BazaarResponse
    anyof_schema_1_validator: Optional[BazaarResponse] = None
    # data type: BazaarResponseSpecialized
    anyof_schema_2_validator: Optional[BazaarResponseSpecialized] = None
    # data type: MarketItemMarketResponse
    anyof_schema_3_validator: Optional[MarketItemMarketResponse] = None
    # data type: MarketRentalsResponse
    anyof_schema_4_validator: Optional[MarketRentalsResponse] = None
    # data type: MarketPropertiesResponse
    anyof_schema_5_validator: Optional[MarketPropertiesResponse] = None
    # data type: MarketLookupResponse
    anyof_schema_6_validator: Optional[MarketLookupResponse] = None
    # data type: TimestampResponse
    anyof_schema_7_validator: Optional[TimestampResponse] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[BazaarResponse, BazaarResponseSpecialized, MarketItemMarketResponse, MarketLookupResponse, MarketPropertiesResponse, MarketRentalsResponse, TimestampResponse]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "BazaarResponse", "BazaarResponseSpecialized", "MarketItemMarketResponse", "MarketLookupResponse", "MarketPropertiesResponse", "MarketRentalsResponse", "TimestampResponse" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = Model8e78be3fa3d353f59f8654fcc1c2199c200Response.model_construct()
        error_messages = []
        # validate data type: BazaarResponse
        if not isinstance(v, BazaarResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BazaarResponse`")
        else:
            return v

        # validate data type: BazaarResponseSpecialized
        if not isinstance(v, BazaarResponseSpecialized):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BazaarResponseSpecialized`")
        else:
            return v

        # validate data type: MarketItemMarketResponse
        if not isinstance(v, MarketItemMarketResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MarketItemMarketResponse`")
        else:
            return v

        # validate data type: MarketRentalsResponse
        if not isinstance(v, MarketRentalsResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MarketRentalsResponse`")
        else:
            return v

        # validate data type: MarketPropertiesResponse
        if not isinstance(v, MarketPropertiesResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MarketPropertiesResponse`")
        else:
            return v

        # validate data type: MarketLookupResponse
        if not isinstance(v, MarketLookupResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MarketLookupResponse`")
        else:
            return v

        # validate data type: TimestampResponse
        if not isinstance(v, TimestampResponse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TimestampResponse`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in Model8e78be3fa3d353f59f8654fcc1c2199c200Response with anyOf schemas: BazaarResponse, BazaarResponseSpecialized, MarketItemMarketResponse, MarketLookupResponse, MarketPropertiesResponse, MarketRentalsResponse, TimestampResponse. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[BazaarResponse] = None
        try:
            instance.actual_instance = BazaarResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[BazaarResponseSpecialized] = None
        try:
            instance.actual_instance = BazaarResponseSpecialized.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[MarketItemMarketResponse] = None
        try:
            instance.actual_instance = MarketItemMarketResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[MarketRentalsResponse] = None
        try:
            instance.actual_instance = MarketRentalsResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[MarketPropertiesResponse] = None
        try:
            instance.actual_instance = MarketPropertiesResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_6_validator: Optional[MarketLookupResponse] = None
        try:
            instance.actual_instance = MarketLookupResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_7_validator: Optional[TimestampResponse] = None
        try:
            instance.actual_instance = TimestampResponse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Model8e78be3fa3d353f59f8654fcc1c2199c200Response with anyOf schemas: BazaarResponse, BazaarResponseSpecialized, MarketItemMarketResponse, MarketLookupResponse, MarketPropertiesResponse, MarketRentalsResponse, TimestampResponse. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], BazaarResponse, BazaarResponseSpecialized, MarketItemMarketResponse, MarketLookupResponse, MarketPropertiesResponse, MarketRentalsResponse, TimestampResponse]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


