# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ReportTypeEnum(str, Enum):
    """
    ReportTypeEnum
    """

    """
    allowed enum values
    """
    MOSTWANTED = 'mostwanted'
    MONEY = 'money'
    STATS = 'stats'
    REFERENCES = 'references'
    FRIENDORFOE = 'friendorfoe'
    COMPANYFINANCIALS = 'companyfinancials'
    TRUELEVEL = 'truelevel'
    STOCKANALYSIS = 'stockanalysis'
    ANONYMOUSBOUNTIES = 'anonymousbounties'
    INVESTMENT = 'investment'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ReportTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


