# coding: utf-8

"""
    Torn API

      * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.  * In case you're using bots to check for changes on openapi.json file, make sure to specificy a custom user-agent header - CloudFlare sometimes prevents requests from default user-agents.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.report_anonymous_bounties import ReportAnonymousBounties
from openapi_client.models.report_company_financials import ReportCompanyFinancials
from openapi_client.models.report_friend_or_foe import ReportFriendOrFoe
from openapi_client.models.report_history import ReportHistory
from openapi_client.models.report_investment import ReportInvestment
from openapi_client.models.report_money import ReportMoney
from openapi_client.models.report_most_wanted import ReportMostWanted
from openapi_client.models.report_stats import ReportStats
from openapi_client.models.report_stock_analysis import ReportStockAnalysis
from openapi_client.models.report_true_level import ReportTrueLevel
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

REPORTREPORTREPORT_ONE_OF_SCHEMAS = ["ReportAnonymousBounties", "ReportCompanyFinancials", "ReportFriendOrFoe", "ReportHistory", "ReportInvestment", "ReportMoney", "ReportMostWanted", "ReportStats", "ReportStockAnalysis", "ReportTrueLevel"]

class ReportReportReport(BaseModel):
    """
    ReportReportReport
    """
    # data type: ReportMoney
    oneof_schema_1_validator: Optional[ReportMoney] = None
    # data type: ReportStats
    oneof_schema_2_validator: Optional[ReportStats] = None
    # data type: ReportMostWanted
    oneof_schema_3_validator: Optional[ReportMostWanted] = None
    # data type: ReportHistory
    oneof_schema_4_validator: Optional[ReportHistory] = None
    # data type: ReportFriendOrFoe
    oneof_schema_5_validator: Optional[ReportFriendOrFoe] = None
    # data type: ReportCompanyFinancials
    oneof_schema_6_validator: Optional[ReportCompanyFinancials] = None
    # data type: ReportTrueLevel
    oneof_schema_7_validator: Optional[ReportTrueLevel] = None
    # data type: ReportStockAnalysis
    oneof_schema_8_validator: Optional[ReportStockAnalysis] = None
    # data type: ReportAnonymousBounties
    oneof_schema_9_validator: Optional[ReportAnonymousBounties] = None
    # data type: ReportInvestment
    oneof_schema_10_validator: Optional[ReportInvestment] = None
    actual_instance: Optional[Union[ReportAnonymousBounties, ReportCompanyFinancials, ReportFriendOrFoe, ReportHistory, ReportInvestment, ReportMoney, ReportMostWanted, ReportStats, ReportStockAnalysis, ReportTrueLevel]] = None
    one_of_schemas: Set[str] = { "ReportAnonymousBounties", "ReportCompanyFinancials", "ReportFriendOrFoe", "ReportHistory", "ReportInvestment", "ReportMoney", "ReportMostWanted", "ReportStats", "ReportStockAnalysis", "ReportTrueLevel" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ReportReportReport.model_construct()
        error_messages = []
        match = 0
        # validate data type: ReportMoney
        if not isinstance(v, ReportMoney):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReportMoney`")
        else:
            match += 1
        # validate data type: ReportStats
        if not isinstance(v, ReportStats):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReportStats`")
        else:
            match += 1
        # validate data type: ReportMostWanted
        if not isinstance(v, ReportMostWanted):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReportMostWanted`")
        else:
            match += 1
        # validate data type: ReportHistory
        if not isinstance(v, ReportHistory):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReportHistory`")
        else:
            match += 1
        # validate data type: ReportFriendOrFoe
        if not isinstance(v, ReportFriendOrFoe):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReportFriendOrFoe`")
        else:
            match += 1
        # validate data type: ReportCompanyFinancials
        if not isinstance(v, ReportCompanyFinancials):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReportCompanyFinancials`")
        else:
            match += 1
        # validate data type: ReportTrueLevel
        if not isinstance(v, ReportTrueLevel):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReportTrueLevel`")
        else:
            match += 1
        # validate data type: ReportStockAnalysis
        if not isinstance(v, ReportStockAnalysis):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReportStockAnalysis`")
        else:
            match += 1
        # validate data type: ReportAnonymousBounties
        if not isinstance(v, ReportAnonymousBounties):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReportAnonymousBounties`")
        else:
            match += 1
        # validate data type: ReportInvestment
        if not isinstance(v, ReportInvestment):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReportInvestment`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ReportReportReport with oneOf schemas: ReportAnonymousBounties, ReportCompanyFinancials, ReportFriendOrFoe, ReportHistory, ReportInvestment, ReportMoney, ReportMostWanted, ReportStats, ReportStockAnalysis, ReportTrueLevel. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ReportReportReport with oneOf schemas: ReportAnonymousBounties, ReportCompanyFinancials, ReportFriendOrFoe, ReportHistory, ReportInvestment, ReportMoney, ReportMostWanted, ReportStats, ReportStockAnalysis, ReportTrueLevel. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ReportMoney
        try:
            instance.actual_instance = ReportMoney.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReportStats
        try:
            instance.actual_instance = ReportStats.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReportMostWanted
        try:
            instance.actual_instance = ReportMostWanted.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReportHistory
        try:
            instance.actual_instance = ReportHistory.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReportFriendOrFoe
        try:
            instance.actual_instance = ReportFriendOrFoe.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReportCompanyFinancials
        try:
            instance.actual_instance = ReportCompanyFinancials.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReportTrueLevel
        try:
            instance.actual_instance = ReportTrueLevel.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReportStockAnalysis
        try:
            instance.actual_instance = ReportStockAnalysis.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReportAnonymousBounties
        try:
            instance.actual_instance = ReportAnonymousBounties.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ReportInvestment
        try:
            instance.actual_instance = ReportInvestment.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ReportReportReport with oneOf schemas: ReportAnonymousBounties, ReportCompanyFinancials, ReportFriendOrFoe, ReportHistory, ReportInvestment, ReportMoney, ReportMostWanted, ReportStats, ReportStockAnalysis, ReportTrueLevel. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ReportReportReport with oneOf schemas: ReportAnonymousBounties, ReportCompanyFinancials, ReportFriendOrFoe, ReportHistory, ReportInvestment, ReportMoney, ReportMostWanted, ReportStats, ReportStockAnalysis, ReportTrueLevel. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ReportAnonymousBounties, ReportCompanyFinancials, ReportFriendOrFoe, ReportHistory, ReportInvestment, ReportMoney, ReportMostWanted, ReportStats, ReportStockAnalysis, ReportTrueLevel]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


